spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/douyin?useSSL=false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


server:
  port: 8080

#mybatis:
#  configuration:
#    logImpl: org.apache.ibatis.logging.log4j2.Log4j2Impl
