name: pr-review
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  review:
    name: ChatGPT code review
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          github_pr_id: ${{ github.event.number }}
          files: 'src/**/*.java'
          openai_model: "gpt-3.5-turbo-0125"
