name: pr-review
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    name: ChatGPT code review
    runs-on: ubuntu-latest
    steps:
      - uses: agogear/chatgpt-pr-review@0.0.11
        with:
          args: ${{ secrets.OPENAI_API_KEY }} ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.id }} "*.py,*.java,*.ts" "gpt-3.5-turbo"
